version: '4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DEV: false
      PORT: $APP_PORT
      JWT_SECRET: $JWT_SECRET
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - todo_network
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    # platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./Docker/PROD/MySQL:/var/lib/mysql
    networks:
      - todo_network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8082:8080
  #   networks:
  #     - todo_network

networks:
  todo_network:
    driver: bridge