version: '4'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - .Docker/MySQL:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080